from fpdf import FPDF
import os
from datetime import datetime

class ReportGenerator(FPDF):
    def header(self):
        # Arial bold 15
        self.set_font('Arial', 'B', 15)
        # Title
        self.cell(0, 10, 'Disease Detection Report', 0, 1, 'C')
        self.ln(5)

    def footer(self):
        # Position at 1.5 cm from bottom
        self.set_y(-15)
        # Arial italic 8
        self.set_font('Arial', 'I', 8)
        # Page number
        self.cell(0, 10, 'Page ' + str(self.page_no()) + '/{nb}', 0, 0, 'C')

def generate_pdf(image, prediction, confidence, details=None):
    """
    Generates a PDF report for the disease detection.
    
    Args:
        image: PIL Image object
        prediction: String name of the predicted disease
        confidence: Float confidence score
        
    Returns:
        bytes: PDF content bytes
    """
    pdf = ReportGenerator()
    pdf.alias_nb_pages()
    pdf.add_page()
    
    # Metadata
    pdf.set_font('Arial', '', 12)
    timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    pdf.cell(0, 10, f"Date: {timestamp}", 0, 1)
    pdf.ln(5)
    
    # Save temp image for PDF (FPDF requires a file path)
    temp_img_path = "temp_report_img.png"
    image.save(temp_img_path)
    
    # Add Image (centered)
    # Get page width
    page_width = pdf.w - 2 * pdf.l_margin
    # We want the image to be roughly 100mm wide
    img_width = 100
    x_centered = (pdf.w - img_width) / 2
    
    try:
        pdf.image(temp_img_path, x=x_centered, w=img_width)
    finally:
        # Clean up temp file
        if os.path.exists(temp_img_path):
            os.remove(temp_img_path)
            
    pdf.ln(10)
    
    # Prediction Results
    pdf.set_font('Arial', 'B', 14)
    pdf.cell(0, 10, "Detection Results", 0, 1)
    
    pdf.set_font('Arial', '', 12)
    pdf.cell(0, 10, f"Predicted Condition: {prediction}", 0, 1)
    pdf.cell(0, 10, f"Confidence Score: {confidence:.2f}%", 0, 1)
    
    pdf.ln(10)
    
    pdf.ln(10)
    
    # Detailed Analysis Section
    if details:
        # Symptoms
        if 'symptoms' in details:
            pdf.set_font('Arial', 'B', 14)
            pdf.cell(0, 10, "Symptoms", 0, 1)
            pdf.set_font('Arial', '', 11)
            for symptom in details['symptoms']:
                pdf.multi_cell(0, 7, f"- {symptom}")
            pdf.ln(5)

        # Cure
        if 'cure' in details:
            pdf.set_font('Arial', 'B', 14)
            pdf.cell(0, 10, "Cure & Treatment", 0, 1)
            pdf.set_font('Arial', '', 11)
            for item in details['cure']:
                pdf.multi_cell(0, 7, f"- {item}")
            pdf.ln(5)

        # Prevention
        if 'prevention' in details:
            pdf.set_font('Arial', 'B', 14)
            pdf.cell(0, 10, "Prevention Tips", 0, 1)
            pdf.set_font('Arial', '', 11)
            for item in details['prevention']:
                pdf.multi_cell(0, 7, f"- {item}")
            pdf.ln(5)

    # General Advice Section
    if not details: # Fallback if no details
        pdf.set_font('Arial', 'B', 14)
        pdf.cell(0, 10, "Recommendation", 0, 1)
        pdf.set_font('Arial', '', 12)
        
        advice = ""
        if prediction == 'Healthy':
            advice = "The crop appears healthy. Continue with regular maintenance and monitoring."
        else:
            advice = f"The crop shows signs of {prediction}. It is recommended to consult with an agricultural expert for specific treatment options. Avoid excessive nitrogen application and monitor water levels."
            
        pdf.multi_cell(0, 10, advice)
    
    pdf.ln(10)
    pdf.set_font('Arial', 'I', 10)
    pdf.multi_cell(0, 10, "Disclaimer: This report is generated by an AI model and should be used as a reference only. Confirm with a field expert before taking action.")

    return pdf.output(dest='S').encode('latin-1')
